[build]
  command = "yarn build"
  publish = "build/"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]

[[redirects]]
  from = "/community/rules"
  to = "/community/code-of-conduct"
